spring.application.name=fitness-app
spring.datasource.url=jdbc:postgresql://db:5432/fitness_tracker
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate для PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Автоматически создавать/обновлять таблицы в базе данных при запуске
spring.jpa.hibernate.ddl-auto=update